# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2943c44f41f95cac83c16c4802d25904057ec0a1581c24c5bd4bbb91b8037ecfb1d14a58b065684e4dd2f281231b610d06cd545d2931b7ae12679b117baf13dc

test:
  secret_key_base: ada1ef6eafd212588bdeba7371ff936c25a39a957adbd9c31e1db3dd757e23156c399bc6d715ee59b190c3a3691891d434492edb61b47bdc3a39182ba28cca18

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
